# -*- coding: utf-8 -*-
"""Per-row triage of the 328 unidentified references (ledger v1.2).

Each entry: REF-ID -> (TRIAGE, CANDIDATE_OR_CORRECTION, REGISTER_KEY, NOTE)

TRIAGE codes
  VL    VERIFIED-LIVE   number + text checked 2026-10-03 against the six Sunni books
                        (tools/verify_sunni.py; evidence in audit/verification/)
  MM    MISMATCH        number / book / place / wording wrong - correction given
  EDN   EDITION-NUMBER  number is from a Bengali or other local edition - map to standard
  CAND  CANDIDATE       specific classical source identified from the research layer;
                        volume/page still to lock (PAGE-CHECK stays)
  SPC   SHIA-PAGE-CHECK Shia source named in ledger is the right book; lock vol/page/hadith
  UNID  UNIDENTIFIED    no classical source known - keep attribution-only wording or drop
  DUP   DUPLICATE       same reference as another row - normalise via REGISTER_KEY
  PROSE PROSE-LINE      a prose sentence carrying "বর্ণিত আছে"; follows its source-block row
  HIST  NON-HADITH      history / geography / poetry / institutional fact
  S181  RESOLVED-S181   covered by sources/S-181_UMM_AYMAN_FADAK_VERIFICATION.md
  Q     QURAN-TEXT      Quran wording check only

REGISTER_KEY groups rows that cite the same reference so the book can carry ONE
canonical citation per key (audit BUG-26 / global normalisation).
"""

T = {
# ---------------- Part 1 ----------------
"REF-001": ("PROSE","","HAD-SHIA-BIGHAYR-HISAB","Prose; follows REF-002."),
"REF-002": ("UNID","Candidate family: Bihar al-Anwar vol. 65 (Shia/ahl al-wilaya enter without reckoning) and vol. 43 (Fatima at qiyama); Amali al-Saduq. Exact wording «يدخلون الجنة بغير حساب» for Fatima + Ali + followers not located.","HAD-SHIA-BIGHAYR-HISAB","SOURCE-MISSING. Keep «বর্ণিত আছে» or drop until a sanad is found."),
"REF-003": ("SPC","al-Kafi 2:536 (Kitab al-Du'a, bab al-du'a 'inda al-nawm; Hisham b. Salim) OR al-Kafi 3:342-343 (bab al-ta'qib). Two valid placements - lock one.","HAD-TASBIH","REF-067 cites vol. 3; REF-003 vol. 2. Both exist; choose one for the book."),
"REF-004": ("CAND","Tirmidhi 614 (Ka'b b. Ujra) and 2616 (Mu'adh): «والصدقة تطفئ الخطيئة كما يطفئ الماء النار»; Ibn Majah 3973 (Mu'adh). All VL.","HAD-SADAQA-NAR","Resolvable now: Tirmidhi 614 / 2616 (sahih per Albani)."),
"REF-005": ("VL","Ibn Majah 2198 (Anas): Ansari man, cup + blanket sold for two dirhams, axe bought. Grade: Albani da'if; Zubair Ali Zai isnad hasan.","","Number correct. Add grading note; also Abu Dawud 1641."),
"REF-006": ("UNID","«চারবার বিয়ে» story - no source in notebook.","","Keep attribution-only or drop."),
"REF-007": ("CAND","Nahj al-Balagha / Ghurar al-Hikam family (Ali a.s.). «ثلاثة مساكين» not located verbatim.","","Needs text to identify; UNID until wording supplied."),
"REF-008": ("CAND","«النظر في وجه العالم عبادة» - Bihar al-Anwar 1:195-205 (Kitab al-'ilm) family; weak, widely quoted.","","Attribution-only wording recommended."),
"REF-009": ("MM","«طلب العلم فريضة على كل مسلم وواضع العلم عند غير أهله كمقلد الخنازير الجوهر» = Ibn Majah 224 (VL; Albani: very da'if). The «اطلبوا العلم ولو بالصين» clause is NOT in Ibn Majah - Ibn Hibban and Ibn al-Jawzi (al-Mawdu'at) call it fabricated. Shia parallel: al-Kafi 1:30 «طلب العلم فريضة».","","Fix: cite Ibn Majah 224 for first clause with grade; label China clause as unsupported."),
"REF-010": ("VL","Tirmidhi 3775 (Ya'la b. Murra): «حسين مني وأنا من حسين أحب الله من أحب حسينا». Grade: hasan (Albani, Shakir).","HAD-HUSAYN-MINNI","Number correct."),
"REF-011": ("MM","«مثل أهل بيتي فيكم كمثل سفينة نوح» is NOT Musnad Ahmad 3786. Sources: al-Hakim, al-Mustadrak 2:343 (h. 3312) and 3:151 (h. 4720); al-Tabarani, al-Awsat 5870, al-Kabir 3:45 (2636-2638); al-Bazzar. Not in the six books (corpus search 2026-10-03: none).","HAD-SAFINA","PRINT BLOCKED on the Ahmad number stays; replace with Hakim/Tabarani after page lock."),
"REF-012": ("VL","Tirmidhi 3713 (Zayd b. Arqam / Abu Sariha): «من كنت مولاه فعلي مولاه» sahih; Tirmidhi 3768: «الحسن والحسين سيدا شباب أهل الجنة» sahih.","HAD-MAWLA; HAD-SHABAB-JANNA","Both numbers correct."),
"REF-013": ("MM","Abu Dawud 5021 is Abu Qatada «الرؤيا من الله والحلم من الشيطان» - neither claim. Correct: Abu Dawud 5019 (Abu Hurayra, «الرؤيا ثلاث») and 5023 (Abu Hurayra, «من رآني في المنام فقد رآني»). Also Bukhari 110, 6993; Muslim 2266. All VL.","HAD-RUYA","Notebook number wrong for both clauses."),
"REF-014": ("UNID","Cheat-list sayings (thoughtless worship, four persons' reward) - no source.","","Keep attribution-only."),
"REF-015": ("HIST","Khwaja Mu'in al-Din Chishti poem - literary; needs diwan reference.","LIT-CHISHTI","Same item as REF-322."),
# ---------------- Part 2 ----------------
"REF-016": ("CAND","«ركعتان بتفكر خير من قيام ليلة» - Bihar al-Anwar 84:240 family (Shia); «الدعاء أفضل العبادة» - Kafi 2:466-467 (bab fadl al-du'a); Sunni: Tirmidhi 3370 «الدعاء هو العبادة» (Nu'man b. Bashir).","","Two separate items; second resolvable."),
"REF-017": ("HIST","Authorial tafsir note; not a citation.","","No action beyond BUG-10 separation."),
"REF-018": ("PROSE","","","Prose; Quran 7:12 confirmed in REF-019."),
"REF-019": ("CAND","«سجدة في كل مكان» offer to Iblis - Shia tafsir family (Tafsir al-Qummi 1:42; Bihar 11:141 ff).","","Keep «বর্ণিত আছে»; lock Qummi page."),
"REF-020": ("UNID","Shu'ba story - notebook only.","","Attribution-only."),
"REF-021": ("SPC","al-Kafi 2:74 (Kitab al-Iman wal-Kufr, bab al-ta'a wal-taqwa), h. 3 - Jabir from Abu Ja'far a.s.: «...وما تنال ولايتنا إلا بالعمل والورع».","","Vol/page identified; lock edition."),
"REF-022": ("MM","«الجنة طيبة لا يدخلها إلا الطيب» is not in Sahih Muslim (corpus search 2026-10-03). Nearest canonical: Muslim 1015 «إن الله طيب لا يقبل إلا طيبا» (different meaning); Tirmidhi 3462 «الجنة طيبة التربة عذبة الماء» (different). ","","PRINT BLOCKED stays. Drop the Muslim attribution; drop or re-source the sentence."),
"REF-023": ("PROSE","","HAD-SARAQU-AYA","Prose; follows REF-032."),
"REF-024": ("PROSE","","HAD-NUQTA","Prose; follows REF-033 / REF-321."),
"REF-025": ("PROSE","","HAD-SALAT-BATRA","Prose; follows REF-034 / REF-303."),
"REF-026": ("PROSE","","","Prose lead-in."),
"REF-027": ("PROSE","","HAD-NUR-AWWAL","Prose; follows REF-041 / REF-154."),
"REF-028": ("HIST","Chapter-level note, not a citation.","","BUG-10: internal note text."),
"REF-029": ("SPC","Tahdhib al-Ahkam 2:289 h. 1157; Tafsir al-Ayyashi 1:19.","","Both plausible; lock edition."),
"REF-030": ("SPC","al-Kafi 3:312-313 (bab qira'at al-Qur'an, h. 1, Mu'awiya b. Ammar).","","thaqalayn.net link given; lock print page."),
"REF-031": ("CAND","al-Hakim, al-Mustadrak 1:232-233 (h. 848-849 in al-Risala numbering): Anas - Mu'awiya omitted basmala, «أسرقت الصلاة أم نسيت». Also al-Shafi'i, al-Umm 1:208; Daraqutni 1:311.","","Hakim number to lock (BUG-21)."),
"REF-032": ("SPC","Tafsir al-Ayyashi 1:21 (h. 14); Bihar al-Anwar 82:20 (Beirut ed. numbering differs: 85:20).","HAD-SARAQU-AYA","Mursal; attribution wording already correct."),
"REF-033": ("SPC","al-Kafi 1:114 h. 1 (Kitab al-Tawhid, bab ma'ani al-asma'): «الباء بهاء الله والسين سناء الله والميم مجد الله» - correct placement.","HAD-NUQTA","Nuqta saying: see REF-321 (NOT VERIFIED)."),
"REF-034": ("SPC","al-Kafi 2:495 (bab al-salat 'ala al-Nabi, h. 21) «لا تبترها»; Amali al-Saduq majlis 36 h. 12.","HAD-SALAT-BATRA","Shia side located. Sunni «الصلاة البتراء» wording: see REF-303."),
"REF-035": ("SPC","al-Kafi 2:18-19 h. 5 (bab da'a'im al-islam, Zurara); Mir'at al-'Uqul 7:102.","HAD-WILAYA-KAFI","Same hadith as REF-284 - normalise."),
"REF-036": ("SPC","al-Kafi 1:219-220 (bab 'ard al-a'mal).","","Lock edition."),
"REF-037": ("SPC","al-Kafi 1:183-184 h. 8 (bab ma'rifat al-imam, Muhammad b. Muslim).","HAD-IMAM-JAHILIYYA","Related to REF-059/083 but different wording - keep separate."),
"REF-038": ("CAND","Ghurar al-Hikam (al-Amidi) no. 4641 (edition numbering varies); not in classical hadith collections.","","Attribution-only correct."),
"REF-039": ("VL","Bukhari 7171 (Ahkam) = Safiyya story (Ali b. Husayn) - correct; parallels Bukhari 2035, 2038, 3101. Muslim 2175 (Safiyya) wording «يبلغ من الإنسان مبلغ الدم» (Bukhari: «يجري من الإنسان مجرى الدم»).","","Numbers correct; note the wording difference between Bukhari and Muslim."),
"REF-040": ("SPC","Nahj al-Balagha, khutba 1 (Subhi Salih ed.) - «أحالها/أجالها» variant.","","Edition lock only."),
"REF-041": ("UNID","First-created light - see REF-154 (Jabir report, disputed).","HAD-NUR-AWWAL","Normalise with REF-154."),
"REF-042": ("SPC","al-Kafi 1:195 h. 5 (bab anna al-a'imma nur Allah, Salih b. Sahl) - correct; sanad has Sahl b. Ziyad.","","Lock page."),
"REF-043": ("VL","Tirmidhi 3786 (Jabir, Arafa): «كتاب الله وعترتي أهل بيتي» - grades: Albani/Shakir sahih, Bashar hasan, Zubair Ali Zai da'if. Muslim 2408 (Zayd b. Arqam): «وأهل بيتي أذكركم الله في أهل بيتي» - VL.","HAD-THAQALAYN","Already correct; register key."),
"REF-044": ("VL","Bukhari 956 (Abu Sa'id: Marwan, «غيرتم والله») and 957 (Ibn Umar: prayer then khutba).","","Numbers correct."),
"REF-045": ("VL","Bukhari 936 (Jabir, twelve men remained); Muslim 863 (Jabir, same event).","","Numbers correct."),
"REF-046": ("SPC","Bihar al-Anwar 27:172-173 h. 16 (Wafa ed.) ← Amali al-Tusi; Thawab al-A'mal p. 197; al-Mahasin p. 91.","HAD-WILAYA-KAFI","Lock edition."),
"REF-047": ("HIST","Maqatil al-Talibiyyin p. 45 (Shamela); Ibn Sa'd 3:24 (DKI); Ibn Kathir, al-Bidaya 7 (vol/page to lock).","","History; «40 years worship» correctly dropped."),
"REF-048": ("PROSE","","HAD-IFTAR-TAMR","Prose; follows REF-049."),
"REF-049": ("EDN","Bukhari «1815» is a Bengali-edition number → standard Bukhari 1954 (Umar: «إذا أقبل الليل من ها هنا ... فقد أفطر الصائم») VL. Iftar with dates/water: Abu Dawud 2356, Tirmidhi 696 (Anas/Salman b. Amir).","HAD-IFTAR-TAMR","Map every Bengali-edition number to standard numbering (BUG-12)."),
"REF-050": ("PROSE","","HAD-MAHR-KHUMS","Prose; follows REF-057 / REF-168."),
"REF-051": ("PROSE","","HAD-KHATAM-RUKU","Prose; follows REF-056 / REF-282."),
"REF-052": ("HIST","Lisan al-'Arab, root r-w-h (تَرْوِيحَة).","","Lexical; page lock."),
"REF-053": ("VL","Bukhari 1129 / Muslim 761 (Aisha): «خشيت أن تفرض عليكم».","","Numbers correct."),
"REF-054": ("VL","Bukhari 2010 (Abd al-Rahman b. Abd al-Qari): «نعمت البدعة هذه».","","Number correct."),
"REF-055": ("SPC","al-Kafi 8:58-63 (al-Rawda, h. 21): khutba «لو قد استوت قدماي ... لرددت فدك».","","Vol/page identified; lock edition."),
"REF-056": ("SPC","Tabari, Jami' al-Bayan on 5:55; al-Kafi 1:288-289 (bab ma nassa Allah... h. 3). Abu Dharr narration: see REF-282 (CAND: al-Tha'labi).","HAD-KHATAM-RUKU","Normalise with REF-282."),
"REF-057": ("SPC","Fiqh al-Rida (p. 294 region, mahr); Bihar al-Anwar 43:105 ff (bab tazwij Fatima) carries the «خمس الدنيا» reports.","HAD-MAHR-KHUMS","Same item as REF-050/168 - normalise."),
"REF-058": ("PROSE","","HAD-ARROW-SALAT","Prose; follows REF-060."),
"REF-059": ("SPC","Kamal al-Din (al-Saduq) 2:409-413 (bab 39); al-Kafi 1:376-377 (bab man dana Allah bi-ghayr imam): «من مات وليس له إمام فميتته ميتة جاهلية». Exact «من مات ولم يعرف إمام زمانه» wording: lock which book carries it.","HAD-IMAM-JAHILIYYA","Keep separate from Muslim 1851 (BUG-06)."),
"REF-060": ("CAND","Arrow removed during prayer - Shia: Bihar al-Anwar 41:17 (manaqib Ali); Manaqib Ibn Shahrashub 2:124. Widely told; weak chain.","HAD-ARROW-SALAT","Attribution-only; lock Bihar page."),
"REF-061": ("HIST","Imam Husayn leaves Mecca 8 Dhu al-Hijja 60 AH - Tabari, Tarikh 5:385; al-Mufid, al-Irshad 2:67.","","History; page lock."),
"REF-062": ("PROSE","","HAD-JAR-DAR","Prose; follows REF-063."),
"REF-063": ("SPC","'Ilal al-Shara'i' 1:181-182 (bab 146); Bihar al-Anwar 43:81-82: Hasan a.s. - «الجار ثم الدار».","HAD-JAR-DAR","Lock edition."),
"REF-064": ("SPC","Tasbih Fatima: Man la yahduruh al-faqih 1:320-321; al-Kafi 3:342-343; Sunni: Bukhari 3705 (VL) servant request.","HAD-TASBIH","Normalise with REF-003/066/067."),
"REF-065": ("VL","Bukhari 1385 (Abu Hurayra): «كل مولود يولد على الفطرة». Also 1358-1359.","HAD-FITRA","Number correct."),
# ---------------- Part 3 ----------------
"REF-066": ("PROSE","","HAD-TASBIH","Prose; follows REF-067."),
"REF-067": ("VL","Bukhari 3705 (Ali a.s.): Fatima complains of the mill → tasbih; also 5361, 6318. al-Kafi 3:342-343 bab al-ta'qib (Shia order 34-33-33).","HAD-TASBIH","Sunni number correct; Shia page lock."),
"REF-068": ("VL","Abu Dawud 5217 (Aisha; Albani sahih) and Tirmidhi 3872 (Aisha; sahih): «ما رأيت أحدا أشبه سمتا ودلا وهديا ... قام إليها».","HAD-QIYAM-FATIMA","Numbers correct. Same as REF-252/262 - normalise."),
"REF-069": ("CAND","«أم أبيها» - Ibn Abd al-Barr, al-Isti'ab 4:1899; Ibn Hajar, al-Isaba 8:262 (entry Fatima); Shia: Bihar al-Anwar 43:19 (from Maqatil al-Talibiyyin).","HAD-UMM-ABIHA","Same as REF-155/255 - normalise."),
"REF-070": ("SPC","Tafsir al-Qummi 2:117 (25:74).","","Q 25:74 confirmed; tafsir page lock."),
"REF-071": ("VL","Abu Dawud 4213 (Thawban) - number correct BUT graded da'if (Albani, Arnaut, Zubair Ali Zai) - add grade. Ibn Umar «فداك أبي وأمي»: al-Hakim al-Mustadrak 3:156 (h. 4737 region) - number to lock (BUG-21).","","Add grading for 4213."),
"REF-072": ("VL","Bukhari 3714 only «فاطمة بضعة مني فمن أغضبها أغضبني». «أنت أعز/ذخر» wording not canonical → attribution-only.","HAD-BIDAA-MINNI","Register key."),
"REF-073": ("VL","Tirmidhi 3874 (Jumay' b. Umayr) - VL but graded MUNKAR (Albani, Shakir); Tirmidhi 3868 (Buraydah) - MUNKAR; Tirmidhi 3819 (Usama) - da'if (Albani) / isnad hasan (Zubair). Abu Hurayra «أيهما أحب إليك» - al-Hakim 3:155 (h. 4735), Tabarani al-Awsat 7675.","HAD-AHABB-FATIMA","Numbers correct; GRADES must be printed (munkar/da'if). Same as REF-161."),
"REF-074": ("HIST","Iqbal, Rumuz-e Bekhudi, section on Sayyida Fatima: «مادر آن مرکز پرکار عشق / مادر آن کاروان سالار عشق» - first word is «مادر» (notebook «مادی» is a typo).","LIT-IQBAL","IDENTIFIED. Fix spelling; cite edition page."),
"REF-075": ("EDN","Bengali-edition numbers 2874, 3446, 6270, 496 → map to standard. «فاطمة عليها السلام» appears in Bukhari 3092, 3093, 3110 («وهي جويرية فأقبلت تسعى» = 3110, Fard al-Khumus), 3705, 3711-3712, 4240-4241, 5361, 6318, 6726 (all VL).","","Map numbers (BUG-12)."),
"REF-076": ("VL","Bukhari 3714 - correct; «من رضيت عنه» clause not canonical.","HAD-BIDAA-MINNI","Normalise."),
"REF-077": ("HIST","Author list - each needs page.","","PAGE-CHECK stays."),
"REF-078": ("S181","al-Ihtijaj recension (deed written then torn).","HAD-FADAK-TESTIMONY","See S-181."),
"REF-079": ("S181","Bukhari 4240-4241, Abu Dawud 2968 (sahih), 2972 (Albani da'if) - all VL today.","HAD-BUKHARI-4240","Grading corrected (BUG-01)."),
"REF-080": ("VL","Muslim 2404 (Sa'd b. Abi Waqqas): Mubahala - «ادع لي عليا وفاطمة وحسنا وحسينا ... هؤلاء أهلي».","HAD-MUBAHALA","Number correct."),
"REF-081": ("S181","Baladhuri (Sunni) + al-Ihtijaj / Sulaym / Ibn Abi al-Hadid (Shia); Aus ibn al-Hadathan = counter-testimony.","HAD-FADAK-TESTIMONY","See S-181."),
"REF-082": ("S181","Ibn Sa'd (mursal); Bihar 29; Hakim NOT VERIFIED.","HAD-UMM-AYMAN-JANNA","See S-181."),
"REF-083": ("VL","Muslim 1851 (Ibn Umar): «من مات وليس في عنقه بيعة مات ميتة جاهلية» - allegiance wording. Shia «لا يعرف إمامه»: see REF-059.","HAD-IMAM-JAHILIYYA","Keep the two wordings separate (BUG-06)."),
"REF-084": ("UNID","Salman's question, mushrik/jahil division - no source.","","Attribution-only."),
"REF-085": ("VL","Bukhari 3624 (Aisha, Masruq): «سيدة نساء أهل الجنة / نساء المؤمنين» - VL; Tirmidhi 3768 - VL.","HAD-SAYYIDA-NISA; HAD-SHABAB-JANNA","Pick one canonical reference per wording (BUG-05)."),
# ---------------- Part 4 ----------------
"REF-086": ("EDN","Kanz al-'Ummal «6/219» = Hyderabad edition; al-Risala ed. 12:109 (h. 34227): «إن الله فطم ابنتي فاطمة وولدها ومن أحبهم من النار». Also Tabarani, al-Awsat; Ibn Asakir.","HAD-FATIMA-NAR","Edition lock; normalise with REF-259."),
"REF-087": ("MM","Notebook says no source - there is one: Muslim 91 (Ibn Mas'ud): «لا يدخل الجنة من كان في قلبه مثقال حبة من خردل من كبر» (VL); also Abu Dawud 4091, Tirmidhi 1998, Ibn Majah 59/4173.","","Resolvable now."),
"REF-088": ("SPC","al-Kafi 2:226-241 (Kitab al-Iman wal-Kufr, bab al-mu'min wa 'alamatuh wa sifatuh).","","Lock hadith number."),
"REF-089": ("SPC","al-Kafi 2:241 h. 39 (bab al-mu'min...): «لا يكون المؤمن مؤمنا حتى يكون فيه ثلاث خصال: سنة من ربه وسنة من نبيه وسنة من وليه»; 'Uyun Akhbar al-Rida 1:256; al-Khisal p. 82.","HAD-RIDA-3SUNAN","Same as REF-216/220 - normalise."),
"REF-090": ("UNID","Four generic sayings - no source.","","Attribution-only or drop."),
"REF-091": ("UNID","«لم يؤمّن الله المؤمن من بلايا الدنيا» type saying - no source.","","Attribution-only."),
"REF-092": ("SPC","Kamal al-Din 2:340 (bab 33) - «يؤمنون بالغيب» = the Qa'im.","","Lock page."),
"REF-093": ("CAND","Sanad chain is al-Saduq's standard chain (Ibn al-Mutawakkil ← al-Himyari ← Ahmad b. Muhammad b. Isa ← Ibn Mahbub ← Ali b. Ri'ab ← Abu Ubayda al-Hadhdha') → al-Khisal or Amali al-Saduq. Locate by the Safa speech text.","","Book identified by chain; page to lock."),
"REF-094": ("CAND","al-Bayhaqi, al-Zuhd al-Kabir no. 373 (Jabir: «قدمتم خير مقدم من الجهاد الأصغر إلى الجهاد الأكبر») - plausible number; chain weak. Sunni canonical: Tirmidhi 1621 «المجاهد من جاهد نفسه» (VL, sahih).","","Add Tirmidhi 1621 as the sound parallel."),
"REF-095": ("CAND","«أعدى عدوك نفسك التي بين جنبيك» - Bayhaqi al-Zuhd 343; al-Daylami; Shia: 'Uddat al-Da'i; Bihar 70:64. Weak.","","Attribution-only correct."),
# ---------------- Part 5 ----------------
"REF-096": ("VL","Short kisa report: Muslim 2424 (Aisha, «مرط مرحل») - VL. Long Jabir version: Shia compilations (REF-190).","HAD-KISA","Resolvable: Muslim 2424."),
"REF-097": ("UNID","Tasnim-related sayings - no source.","","Attribution-only."),
"REF-098": ("CAND","«من مات على حب آل محمد مات شهيدا» - al-Zamakhshari, al-Kashshaf on 42:23 (Egypt ed. 3:467); al-Razi, Mafatih al-Ghayb 27:166; al-Qurtubi 16:22. Not in six books (corpus: none).","","Page lock; tafsir attribution correct."),
"REF-099": ("CAND","98:7 «أنت يا علي وشيعتك» - al-Suyuti, al-Durr al-Manthur 6:379 (from Ibn Asakir, Jabir); al-Tabari, Jami' al-Bayan 30:171. NB: Muslim 2369 «يا خير البرية - ذاك إبراهيم» is a different hadith.","","Page lock."),
"REF-100": ("UNID","Arabic texts about 'ashiqun - no source.","","Attribution-only or drop."),
"REF-101": ("MM","Local Windows path used as citation (BUG-07). Replace with: Tafsir Hubb-e Ali, Surat al-Kawthar h. 10-11 (hubbeali.com h. 9499); al-Ihtijaj for h. 11.","","Remove F:\\ path from manuscript."),
"REF-102": ("HIST","An Enlightening Commentary vol. 20, Surat al-Kawthar.","","Page lock."),
"REF-103": ("CAND","«إن الله جعل ذرية كل نبي في صلبه وجعل ذريتي في صلب علي» - al-Tabarani, al-Kabir 3:43 (h. 2630); al-Khatib, Tarikh Baghdad 1:316-317; Kanz al-'Ummal 11:600. Not in six books.","","Page lock."),
"REF-104": ("CAND","Virtue of reciting al-Kawthar - Thawab al-A'mal (al-Saduq) p. 126 region.","","Lock."),
"REF-105": ("MM","Notebook says no source - Bukhari 4966 (Ibn Abbas via Sa'id b. Jubayr): «الكوثر الخير الذي أعطاه الله إياه» VL.","","Resolvable now."),
"REF-106": ("CAND","Mubahala narrative: al-Durr al-Manthur 2:38-39 (Egypt ed.) on 3:61; al-Baydawi; al-Jalalayn; al-Zamakhshari, al-Kashshaf 1:368-370 (the «banar/khinzir» warning).","HAD-MUBAHALA","Page lock."),
"REF-107": ("EDN","Muslim 2404 (VL) standard; Bengali ed. «6062 / p. 917» is edition-specific.","HAD-MUBAHALA","Use 2404."),
"REF-108": ("CAND","«أنا ميزان العلم وعلي كفتاه والحسن والحسين خيوطه وفاطمة علاقته...» - Ibn Shahrashub, al-Manaqib 3:? / Bihar al-Anwar 40:? ; Qunduzi, Yanabi' al-Mawadda. Weak, late.","","Attribution-only."),
"REF-109": ("CAND","76:8-9 nuzul story - al-Zamakhshari, al-Kashshaf 4:670; al-Tabrisi, Majma' al-Bayan 10:209; Shawahid al-Tanzil 2:393 ff.","","Page lock."),
"REF-110": ("DUP","Cross-reference to REF-097/100.","","No separate action."),
# ---------------- Part 6 ----------------
"REF-111": ("HIST","Topography of Fatima's house; map is illustrative.","","Already labelled."),
"REF-112": ("PROSE","","","Prose; follows REF-115 (UNID)."),
"REF-113": ("SPC","Tafsir al-Qummi 2:376 (Surat al-Tahrim); Bihar al-Anwar 22:516-517.","","Lock page/wording."),
"REF-114": ("SPC","al-Kafi 1:451-452 (bab mawlid al-Nabi, burial ten by ten).","","Lock."),
"REF-115": ("UNID","Ali shows Abu Bakr «by the hand» (Q 3:169) - no source.","","Attribution-only or drop."),
"REF-116": ("HIST","Fadak: Yaqut, Mu'jam al-Buldan 4:238 (entry فدك); distance figure modern.","","Geography; cite Yaqut."),
"REF-117": ("SPC","al-Ihtijaj (al-Khurasan ed.) 1:131-149 (khutbat Fadak); Balaghat al-Nisa' (Ibn Tayfur) pp. 23-30.","HAD-FADAK-KHUTBA","Lock edition; link S-181 §3-D edition choice."),
"REF-118": ("SPC","al-Ihtijaj 1:131 (Abdullah b. al-Hasan: she came veiled).","HAD-FADAK-KHUTBA","Lock."),
"REF-119": ("SPC","Bihar al-Anwar 43:177 (Bayt al-Ahzan).","","Lock."),
"REF-120": ("CAND","Musa's tongue that never disobeyed - 'Uddat al-Da'i (Ibn Fahd al-Hilli); other items oral.","","Attribution-only."),
"REF-121": ("CAND","17:26 → Fadak given to Fatima (Abu Sa'id): al-Durr al-Manthur 4:177 (Egypt ed.) from al-Bazzar, Abu Ya'la, Ibn Abi Hatim, Ibn Mardawayh; Tabarani not the primary carrier.","HAD-FADAK-1726","Same chain as REF-137/138 - normalise."),
"REF-122": ("S181","Baladhuri Futuh; Tabari; Ibn Abi al-Hadid, Sharh 16:213-216 (deed torn). «Suyuti, Tarikh al-Khulafa» for the tearing - not located; drop unless page found.","HAD-FADAK-TESTIMONY","See S-181 §3."),
"REF-123": ("VL","Muslim 1759 (Aisha) VL; Bukhari 3093 (Khumus) and 6726 (Fara'id) VL: «لا نورث ما تركنا صدقة».","HAD-LA-NURITH","Numbers correct."),
"REF-124": ("SPC","al-Kafi 2:399-400 (bab al-shakk).","","Lock."),
"REF-125": ("UNID","Fadak as Khadija's mahr - no classical source known.","","Recommend removal or «কেউ কেউ বলেন»."),
"REF-126": ("VL","Bukhari 4240 - text VL incl. «فهجرته فلم تكلمه حتى توفيت».","HAD-BUKHARI-4240","Bengali ed. number to map."),
"REF-127": ("Q","30:38 «فَآتِ ذَا الْقُرْبَى» vs 17:26 «وَآتِ ذَا الْقُرْبَى» - correct distinction.","","Quran text only."),
"REF-128": ("SPC","al-Hasakani, Shawahid al-Tanzil 1:570-575 (h. 606-611) on 30:38.","","Lock."),
"REF-129": ("CAND","Fatima's elegy «صبت علي مصائب لو أنها...» - Bihar al-Anwar 43:175-176; Manaqib Ibn Shahrashub 3:?","","Attribution-only; lock."),
"REF-130": ("SPC","Bihar al-Anwar 43:6-9 (age), 43:212-215 (duration after the Prophet).","HAD-BIHAR43-AGE","Same as REF-135 - normalise."),
"REF-131": ("MM","Audit note over-corrects: Bukhari 4240 DOES contain «فلما توفيت دفنها زوجها علي ليلا ولم يؤذن بها أبا بكر وصلى عليها» (VL 2026-10-03). Only the wasiyya-to-conceal-the-grave wording is absent (Shia: Bihar 43:183 ff).","HAD-BUKHARI-4240","Night burial + not informing Abu Bakr → CONFIRMED from 4240; concealment wasiyya → Shia source."),
"REF-132": ("VL","Bukhari 3623-3624; Muslim 2450 (Aisha, Masruq) - VL.","","Wording check only."),
"REF-133": ("CAND","Imam Kazim and Harun on Fadak's borders - Bihar al-Anwar 48:144 (from Manaqib Ibn Shahrashub 4:320).","","Lock."),
"REF-134": ("VL","Pen-and-paper: Bukhari 114, 4431 (VL), also 3053, 4432, 5669, 7366; Muslim 1637 (VL). «Ka'ba does not go to people» - saying, no source.","HAD-QALAM","Resolvable."),
"REF-135": ("DUP","Same as REF-130.","HAD-BIHAR43-AGE","Normalise."),
"REF-136": ("SPC","al-Kafi 1:543 h. 5 (bab al-fay' wal-anfal): Imam Sadiq on 17:26 and Fadak.","HAD-FADAK-1726","Lock."),
"REF-137": ("CAND","Same Abu Sa'id chain (Bazzar, Abu Ya'la, Ibn Abi Hatim, Ibn Mardawayh) = al-Durr al-Manthur 4:177 on 17:26; Zayn al-Abidin and the Syrian: Tabari? → more likely Majma' al-Bayan 6:634 / Bihar 45:?; Mi'raj al-Nubuwwa is a Persian secondary.","HAD-FADAK-1726","Normalise with REF-121."),
"REF-138": ("CAND","Atiyya al-Awfi ← Abu Sa'id: same chain; Majma' al-Bayan 6:634.","HAD-FADAK-1726","Normalise."),
"REF-139": ("SPC","'Uyun Akhbar al-Rida 1:228-239 (bab 23; Rayyan b. al-Salt; the «اصطفى» debate with al-Ma'mun).","","Lock."),
"REF-140": ("UNID","Aban b. Taghlib reports - book not named.","","Needs text."),
"REF-141": ("CAND","Umm Hani / Abu Bakr - the «vol. 4 p. 81» is Sharh Nahj al-Balagha numbering (Ibn Abi al-Hadid quoting al-Jawhari, al-Saqifa wa Fadak); check Sharh 16:214-215 and al-Jawhari (ed. Amini) pp. 103-104.","HAD-FADAK-TESTIMONY","Link S-181."),
# ---------------- Part 7 ----------------
"REF-142": ("VL","Bukhari 3714 - VL. «ويسرني ما يسرها» family: Muslim 2449 / Bukhari 5230 «يريبني ما أرابها / يؤذيني ما آذاها» (VL).","HAD-BIDAA-MINNI","Normalise."),
"REF-143": ("VL","Bukhari 7222 (Jabir b. Samura: «اثنا عشر أميرا ... كلهم من قريش»); Muslim 1821-1822 («اثنا عشر خليفة») - VL.","HAD-12-KHALIFA","Resolvable."),
"REF-144": ("VL","Tirmidhi 3206 (Anas): «كان يمر بباب فاطمة ستة أشهر ... الصلاة يا أهل البيت» - VL; grade da'if (Albani/Shakir/Zubair).","HAD-BAB-FATIMA-SALAT","Add grade; normalise with REF-187/189/269/274."),
"REF-145": ("MM","Audit-note language inside source block (BUG-09).","","Move cleanup note to ledger."),
"REF-146": ("CAND","Ibn Mas'ud «إن الله أمرني أن أزوج فاطمة من علي» - al-Tabarani, al-Kabir 10:156 (h. 10305); al-Khatib, Tarikh Baghdad 4:195; Kanz 13:?","HAD-TAZWIJ","Page lock; weak chains."),
"REF-147": ("CAND","Anas «أتدري ما جاءني به جبريل» - al-Khwarizmi, al-Manaqib; Ibn Hajar al-Haytami, al-Sawa'iq; Qunduzi, Yanabi' 2:? Late Sunni compilations.","HAD-TAZWIJ","Attribution-only."),
"REF-148": ("CAND","40,000 angels / Tuba tree - al-Khwarizmi, al-Manaqib; Yanabi' al-Mawadda; Shia: Bihar 43:103 ff.","HAD-TAZWIJ","Attribution-only."),
"REF-149": ("CAND","«زوجتها من علي في الملأ الأعلى» - Yanabi' al-Mawadda; Bihar 43:?","HAD-TAZWIJ","Attribution-only."),
"REF-150": ("CAND","«اللهم إني أعيذها بك وذريتها من الشيطان الرجيم» - Abd al-Razzaq / Ibn Sa'd 8:24 (Asma'); Kanz; Bihar 43:?","HAD-TAZWIJ","Lock."),
"REF-151": ("CAND","Buraydah «اللهم بارك فيهما وبارك عليهما وبارك لهما في شبليهما» - al-Tabarani, al-Kabir 2:20 (h. 1153); al-Haythami, Majma' al-Zawa'id 9:209.","HAD-TAZWIJ","Lock."),
"REF-152": ("DUP","Same as REF-143.","HAD-12-KHALIFA","Normalise."),
"REF-153": ("DUP","Same as REF-072/142.","HAD-BIDAA-MINNI","Normalise."),
"REF-154": ("CAND","Jabir «أول ما خلق الله نور نبيك» - attributed to Abd al-Razzaq (lost part of the Musannaf); quoted by al-Qastallani, al-Mawahib 1:71 and al-Zurqani; disputed/absent in extant works. Shia: Bihar 15:24, 25:21-22.","HAD-NUR-AWWAL","Attribution-only wording mandatory."),
"REF-155": ("DUP","Same as REF-069.","HAD-UMM-ABIHA","Normalise."),
"REF-156": ("CAND","«كتاب الله وسنتي» - al-Hakim, al-Mustadrak 1:93 (h. 318-319; Ibn Abbas, weak chain); Malik, al-Muwatta' (balaghan) 2:899 (h. 1395 Risala numbering).","HAD-KITAB-SUNNA","Numbers plausible; lock edition (BUG-21)."),
"REF-157": ("VL","Muslim 2408, Tirmidhi 3786, 3788 - all VL. Abu Sa'id and Zayd b. Thabit versions: Ahmad 11104, 21578 (lock).","HAD-THAQALAYN","Normalise."),
"REF-158": ("VL","Bukhari 114, 4431 VL; Muslim 1637 VL; Ahmad 3/346; Bihar 22:468-469; al-Irshad 1:184.","HAD-QALAM","Normalise with REF-134."),
"REF-159": ("UNID","Oral exegesis (father) - not a citation.","","Attribution-only."),
"REF-160": ("CAND","Miswar «فاطمة شجنة مني» - al-Hakim 3:154 (h. 4732 region); Ahmad 18913 (Miswar: «يقبضني ما يقبضها»). Six-book corpus: «شجنة» only in unrelated hadith (Bukhari 5989).","","Hakim number lock (BUG-21)."),
"REF-161": ("CAND","Abu Hurayra: Ali asked «أيما أحب إليك أنا أو فاطمة» → «فاطمة أحب إلي منك وأنت أعز علي منها» - al-Hakim 3:155 (h. 4735); Tabarani al-Awsat 7675. «Ibn Abi Nujayh» in notebook is probably a garbled rawi name.","HAD-AHABB-FATIMA","Normalise with REF-073."),
"REF-162": ("PROSE","","","Prose; follows REF-163."),
"REF-163": ("CAND","al-Tha'labi, al-Kashf wal-Bayan 5:303 on 13:43 (Abdullah b. Ata ← Abdullah b. Salam); Shawahid al-Tanzil 1:400-405.","","Lock."),
"REF-164": ("CAND","«أنا مدينة العلم وعلي بابها» - al-Hakim 3:126-127 (h. 4637-4639); al-Tabarani, al-Kabir 11:65 (h. 11061); al-Khatib, Tarikh Baghdad 11:48-50. NOT in Tirmidhi; Tirmidhi 3723 is «أنا دار الحكمة وعلي بابها» (VL; da'if). Corpus 2026-10-03: «مدينة العلم» absent from six books.","HAD-MADINAT-ILM","Five rows (164/207/240/245/309) - one register entry."),
"REF-165": ("SPC","Ahl al-dhikr = the Imams: al-Kafi 1:210-212 (bab anna ahl al-dhikr ... hum al-a'imma).","","Lock."),
"REF-166": ("SPC","Tafsir al-Imam al-Askari (attributed) p. 345 region; Bihar al-Anwar 2:3-4.","","Lock; note attribution dispute."),
"REF-167": ("PROSE","","HAD-UMM-TAWAF","Prose; follows REF-171."),
"REF-168": ("DUP","Same as REF-057.","HAD-MAHR-KHUMS","Normalise."),
"REF-169": ("SPC","al-Kafi 1:537-538 (bab silat al-imam).","HAD-DIRHAM-YATIM","Same as REF-170."),
"REF-170": ("SPC","al-Kafi 1:537-538 (bab silat al-imam) - 57:11 exegesis; «درهم ... أعظم من أحد».","HAD-DIRHAM-YATIM","Lock."),
"REF-171": ("CAND","Mother on shoulders at tawaf «ولا بزفرة واحدة» - Shia: al-Kafi 2:162-163 (bab al-birr bil-walidayn); Sunni: al-Bayhaqi, Shu'ab al-Iman 7:502 (h. 7905 region); al-Bazzar. Not in six books (corpus: none).","HAD-UMM-TAWAF","Lock."),
"REF-172": ("PROSE","","HAD-SIRAT-ALI","Prose; see REF-173-175."),
"REF-173": ("SPC","Shawahid al-Tanzil 1:66 ff (on 1:6).","HAD-SIRAT-ALI","Lock."),
"REF-174": ("SPC","Ma'ani al-Akhbar (al-Saduq) p. 32-33 (الصراط: two paths; thinner than a hair); Tafsir al-Qummi / al-Ayyashi on 67:22.","HAD-SIRAT-ALI","Lock."),
"REF-175": ("UNID","«sun, moon, Venus, two stars» - no source.","","Attribution-only."),
"REF-176": ("PROSE","","HAD-SIRAT-ALI","Prose; follows REF-178."),
"REF-177": ("CAND","Yanabi' al-Mawadda (Qunduzi) quoting al-Manaqib - late Sunni compilation.","HAD-SIRAT-ALI","Lock vol/page."),
"REF-178": ("SPC","Tafsir al-Ayyashi 1:383-384 on 6:153: «هو والله علي، هو والله الصراط والميزان».","HAD-SIRAT-ALI","Lock."),
# ---------------- Part 8 ----------------
"REF-179": ("CAND","«أنا المنذر وعلي الهادي» (13:7) - al-Tabari, Jami' al-Bayan 13:72 (Ibn Abbas); Shawahid al-Tanzil 1:381-395; Ibn Asakir, Tarikh Dimashq 42:359; Ibn Mardawayh.","HAD-ANA-MUNDHIR","Lock."),
"REF-180": ("CAND","Three views on 13:7 - al-Tabari 13:72.","HAD-ANA-MUNDHIR","Lock."),
"REF-181": ("CAND","Abu Bakr al-Hadrami al-Shafi'i, Rashfat al-Sadi (Abu al-Aliya); Ma'ani al-Akhbar.","","Lock."),
"REF-182": ("SPC","al-Kafi 1:208 h. 1-2 (bab anna ahl al-dhikr / «كونوا مع الصادقين»: «إيانا عنى»).","","Lock."),
"REF-183": ("SPC","Nahj al-Balagha, hikma 458 (Subhi Salih) / 455 other eds.","","Edition lock."),
"REF-184": ("SPC","'Uyun Akhbar al-Rida 2:51 h. 197; Mishkat al-Anwar 1:116.","","Lock edition."),
"REF-185": ("HIST","Madrasa-i-Aliya history (Islamic Foundation).","","Page lock."),
"REF-186": ("VL","Umm Salama «أنت على مكانك وأنت على خير» - Tirmidhi 3871 (Umm Salama, sahih) VL; Tirmidhi 3205 & 3787 (Umar b. Abi Salama) VL.","HAD-KISA","Resolvable."),
"REF-187": ("CAND","Ibn Abbas nine months: Shawahid al-Tanzil 2:11-14; Abu al-Hamra: al-Tabarani, al-Kabir 22:200; Anas: Tirmidhi 3206 (VL, da'if).","HAD-BAB-FATIMA-SALAT","Normalise."),
"REF-188": ("VL","Muslim 2424 (Aisha) VL - CONFIRMED stands; others lock.","HAD-KISA","Normalise."),
"REF-189": ("CAND","Anas at the door - Shawahid al-Tanzil 2:11 ff; Tirmidhi 3206 (VL).","HAD-BAB-FATIMA-SALAT","Normalise."),
"REF-190": ("SPC","Long Jabir kisa: 'Awalim al-'Ulum 11:930-934; Mafatih al-Jinan.","HAD-KISA","Lock."),
"REF-191": ("CAND","Abu Dharr at the Ka'ba door - al-Hakim 2:343 (h. 3312) & 3:151 (h. 4720); Tabarani.","HAD-SAFINA","Normalise with REF-011/208."),
"REF-192": ("SPC","98:5 ta'wil - Ta'wil al-Ayat 2:813; Bihar 24:?","HAD-98-5","Same as REF-270."),
"REF-193": ("CAND","«لا خير فيمن لا يتحبب ولا يتبغض» - Ghurar al-Hikam / Tuhaf al-'Uqul family.","","Lock."),
"REF-194": ("SPC","Nahj al-Balagha khutba 179 (Dhi'lib al-Yamani).","HAD-NAHJ-179","Same as REF-195."),
"REF-195": ("SPC","Nahj al-Balagha khutba 179 (Subhi Salih).","HAD-NAHJ-179","Edition lock."),
"REF-196": ("UNID","Rebuke of the «behind seven heavens» oath - no source.","","Attribution-only."),
"REF-197": ("SPC","al-Kafi 1:89 h. 5 (Kitab al-Tawhid, bab al-kawn wal-makan): the Jewish scholar «متى كان ربنا».","","Lock."),
"REF-198": ("HIST","Ibn Hisham, al-Sira 1:482-483 (laylat al-mabit).","","Page lock."),
"REF-199": ("UNID","«same light» reason - Bihar vol. 5 citation unclear.","","Needs text."),
"REF-200": ("CAND","3:195 «الذكر علي والأنثى فاطمة» - Shia tafsir (Bihar 36:?; Manaqib Ibn Shahrashub).","","Attribution-only."),
"REF-201": ("VL","«من رآني في المنام فقد رآني» - Bukhari 110, 6993 VL; Muslim 2266 VL; Abu Dawud 5023 VL.","HAD-RUYA","Resolvable; normalise with REF-013."),
"REF-202": ("VL","Bukhari 1350 (Jabir: Abdullah b. Ubayy, shirt) VL; «1000 Khazraji» - no source.","","Number correct."),
"REF-203": ("HIST","Ibn Hisham, al-Sira 1:480 ff.","","Page lock."),
"REF-204": ("SPC","Kamal al-Din (Yunus b. Zibyan); Kifayat al-Athar (al-Khazzaz) - lock pages; chain weak.","","Lock; flag chain."),
# ---------------- Part 9 ----------------
"REF-205": ("PROSE","","","Prose; follows REF-209 (UNID)."),
"REF-206": ("VL","Muslim 2408; Tirmidhi 3786; Tirmidhi 3788 VL (Albani sahih; Zubair da'if).","HAD-THAQALAYN","3788 PAGE-CHECK → VERIFIED."),
"REF-207": ("DUP","See REF-164.","HAD-MADINAT-ILM","Normalise."),
"REF-208": ("DUP","See REF-011/191.","HAD-SAFINA","Normalise."),
"REF-209": ("UNID","«أحبوني ... أحبوا وليي» - not located.","","Attribution-only or drop."),
"REF-210": ("Q","42:23 Bengali rendering check.","","Quran text."),
"REF-211": ("PROSE","","","Prose; follows REF-212."),
"REF-212": ("SPC","Tafsir al-Qummi 2:106-107 on 24:40 («الظلمات الأول وصاحبه ... سحاب معاوية وفتن بني أمية»).","","Lock."),
"REF-213": ("SPC","Nahj al-Balagha khutba 50.","","Edition lock."),
"REF-214": ("SPC","Nahj al-Balagha khutba 93 («فقأت عين الفتنة»).","","Edition lock."),
"REF-215": ("UNID","Story of halal/haram seeker - no source.","","Attribution-only."),
"REF-216": ("PROSE","","HAD-RIDA-3SUNAN","Prose; follows REF-089/220."),
"REF-217": ("SPC","al-Kafi 1:54-58 (bab al-bida' wal-ra'y wal-maqayis): h. 3, 4, 5, 8 as listed.","HAD-BIDAA-KAFI","Lock page."),
"REF-218": ("SPC","al-Kafi 2:415-416 (bab al-kufr) «أدنى ما يخرج به الرجل من الإيمان...».","","Lock."),
"REF-219": ("UNID","Man in chains story - not in al-Kafi (log B3).","","Attribution-only."),
"REF-220": ("DUP","See REF-089.","HAD-RIDA-3SUNAN","Normalise."),
"REF-221": ("SPC","al-Kafi 1:58 h. 19: «حلال محمد حلال أبدا إلى يوم القيامة وحرامه حرام أبدا».","","Lock."),
"REF-222": ("PROSE","","","Prose; follows REF-223."),
"REF-223": ("VL","Tirmidhi 2951 (Ibn Abbas): «اتقوا الحديث عني إلا ما علمتم ... ومن قال في القرآن برأيه» VL; grade da'if (Albani).","","Add grade."),
"REF-224": ("DUP","Same hadith as REF-223 (Tirmidhi 2951).","","Normalise."),
"REF-225": ("VL","Abu Dawud 3652 (Jundub) VL - da'if; Tirmidhi 2952 VL - da'if.","","Add grades."),
"REF-226": ("SPC","al-Kafi 1:54 h. 6 = Nahj khutba 17 («رجلان ... أبغض الخلائق»).","HAD-BIDAA-KAFI","Lock."),
"REF-227": ("SPC","Nur al-Thaqalayn 1:607 (5:15); Tafsir al-Ayyashi 1:323.","","Lock."),
"REF-228": ("UNID","Prophet to Jabir «باب العلم» - not located.","","Attribution-only."),
"REF-229": ("CAND","«أنت الطريق الواضح والصراط المستقيم ويعسوب المؤمنين» - Amali al-Tusi / Bihar al-Anwar 38:?","","Lock."),
"REF-230": ("CAND","«نحن الصراط» - Ma'ani al-Akhbar p. 35; Bihar 24:11.","HAD-SIRAT-ALI","Lock."),
"REF-231": ("DUP","Same as REF-226.","HAD-BIDAA-KAFI","Normalise."),
"REF-232": ("CAND","Imam Husayn's wasiyya to Muhammad b. al-Hanafiyya («إنما خرجت لطلب الإصلاح...») - Bihar al-Anwar 44:329-330; al-Khwarizmi, Maqtal 1:188.","","Lock."),
"REF-233": ("PROSE","","HAD-MAWLA","Prose; follows REF-237."),
"REF-234": ("PROSE","","","Prose; follows REF-239 (UNID)."),
"REF-235": ("SPC","32:24 on Fatima's descendants - Tafsir al-Qummi 2:170; Bihar 24:?","","Lock."),
"REF-236": ("VL","Bukhari 3706 (Sa'd): «أما ترضى أن تكون مني بمنزلة هارون من موسى» VL; Muslim 2404 VL.","HAD-MANZILA","Numbers correct."),
"REF-237": ("VL","Tirmidhi 3713 VL. Congratulation «بخ بخ لك يا ابن أبي طالب»: Ahmad 18479/18502 (al-Bara'); Ibn Majah 116 lacks it. Six-book corpus: not found.","HAD-MAWLA","Lock Ahmad number."),
"REF-238": ("SPC","Tafsir al-Qummi 1:36; Nur al-Thaqalayn 1:52; al-Kafi 1 (Hujja).","","Lock."),
"REF-239": ("UNID","«fourth khalifa» saying - not located.","","Attribution-only or drop."),
"REF-240": ("VL","«اثنا عشر خليفة كلهم من قريش» Bukhari 7222 / Muslim 1821 VL; «خلافة النبوة ثلاثون سنة» Abu Dawud 4646 VL, Tirmidhi 2226 VL. «أنت وصيي وخليفتي», «لكل نبي وصي» - Shia sources + late Sunni (Tabarani, Daylami) - CAND; madinat al-ilm - see HAD-MADINAT-ILM.","HAD-12-KHALIFA; HAD-MADINAT-ILM","Split: two VL, rest CAND."),
"REF-241": ("CAND","al-Zamakhshari, al-Kashshaf 3:514 (32:23-24).","","Lock."),
"REF-242": ("VL","Thaqalayn - see REF-206.","HAD-THAQALAYN","Normalise."),
"REF-243": ("SPC","al-Kafi 1:478-479 h. 4 (bab mawlid Abi al-Hasan Musa a.s.) - the Christian scholar: «حم محمد ... الكتاب المبين أمير المؤمنين ... الليلة المباركة فاطمة».","","Lock."),
"REF-244": ("UNID","«كنت أنا وعلي وفاطمة والحسن والحسين ... قبل آدم بألف عام» - not located verbatim; nur hadith family.","HAD-NUR-AWWAL","Attribution-only."),
"REF-245": ("DUP","See REF-164.","HAD-MADINAT-ILM","Normalise."),
"REF-246": ("PROSE","","HAD-ZAHRA-NAME","Prose; follows REF-249/291."),
"REF-247": ("SPC","'Ilal al-Shara'i' 1:5-6 (bab 2?); Bihar 15:?","","Lock."),
"REF-248": ("UNID","Angels surround Iblis, throw into sea - not located.","","Attribution-only."),
"REF-249": ("SPC","'Ilal al-Shara'i' 1:180-181 (bab 142: «لم سميت فاطمة الزهراء»); Bihar al-Anwar 43:12.","HAD-ZAHRA-NAME","Lock; normalise with REF-289/291."),
"REF-250": ("VL","Bukhari 3714 VL.","HAD-BIDAA-MINNI","Normalise."),
"REF-251": ("CAND","«إن الله يغضب لغضبك ويرضى لرضاك» - al-Hakim 3:154 (h. 4730) - number plausible; lock edition (BUG-21). Six-book corpus: none.","","Lock."),
"REF-252": ("VL","Aisha standing/kissing/seating - Abu Dawud 5217, Tirmidhi 3872 VL.","HAD-QIYAM-FATIMA","Normalise with REF-068."),
"REF-253": ("CAND","Gate of Paradise inscription - al-Khatib, Tarikh Baghdad 7:387 region; weak.","","Attribution-only."),
"REF-254": ("SPC","Tafsir Furat al-Kufi - lock page.","","Lock."),
"REF-255": ("DUP","See REF-069.","HAD-UMM-ABIHA","Normalise."),
"REF-256": ("PROSE","","HAD-FATIMA-NAR","Prose; follows REF-259."),
"REF-257": ("PROSE","","","Prose; follows REF-260."),
"REF-258": ("VL","Tirmidhi 3788 VL (contains «لن يتفرقا حتى يردا علي الحوض»).","HAD-THAQALAYN","PAGE-CHECK → VERIFIED."),
"REF-259": ("CAND","«إن الله غير معذبك ولا ولدك» - al-Tabarani, al-Kabir 11:263 (h. 11685 region), Majma' al-Zawa'id 9:202; «أحصنت فرجها فحرمها الله وذريتها على النار» - al-Hakim 3:152 (h. 4726), Tabarani; «فطمها الله وفطم محبيها» - Kanz 12:109. None in six books (corpus).","HAD-FATIMA-NAR","Lock; normalise with REF-086."),
"REF-260": ("CAND","Tabarani, al-Kabir (Ibn Abbas) - weak; keep attribution.","","Lock number."),
"REF-261": ("VL","Hadith qudsi «يا ابن آدم ... عنان السماء» - Tirmidhi 3540 (Anas) VL; sahih (Albani).","","Resolvable."),
"REF-262": ("VL","Aisha resemblance - Abu Dawud 5217 / Tirmidhi 3872 VL; «مرحبا بابنتي» Bukhari 3623-3624 VL; Hasan resembles the Prophet - Bukhari 3752 VL.","HAD-QIYAM-FATIMA","Resolvable."),
# ---------------- Part 10 ----------------
"REF-263": ("PROSE","","","Prose; follows REF-265 (UNID)."),
"REF-264": ("VL","Muslim 395 (Abu Hurayra): «قسمت الصلاة بيني وبين عبدي نصفين» VL.","","Number correct."),
"REF-265": ("UNID","«إذا أردت أن يحدثك الله فاقرأ القرآن» - not located.","","Attribution-only."),
"REF-266": ("UNID","«الصلاة معراج المؤمن» - no hadith source (later saying).","","Keep «বলা হয়»."),
"REF-267": ("PROSE","","","Prose; follows REF-272 (UNID)."),
"REF-268": ("PROSE","","","Prose; follows REF-273."),
"REF-269": ("PROSE","","HAD-BAB-FATIMA-SALAT","Prose; follows REF-274."),
"REF-270": ("SPC","98:5 - Ta'wil al-Ayat 2:813.","HAD-98-5","Normalise with REF-192."),
"REF-271": ("VL","«مفتاح الجنة الصلاة ومفتاح الصلاة الوضوء» - Tirmidhi 4 (Jabir) VL (Albani sahih; Zubair da'if); Ahmad 14662.","","Resolvable with grade."),
"REF-272": ("UNID","«الصلاة حيث أنا» - not located; bazaar inspection - Sunni/Shia history (Kanz, Bihar 40).","","Attribution-only."),
"REF-273": ("VL","Abu Sa'id b. al-Mu'alla - Bukhari 4474 VL (also 4703, 5006). Salman part - not located.","","Resolvable."),
"REF-274": ("VL","Tirmidhi 3206 VL (six months; da'if).","HAD-BAB-FATIMA-SALAT","Normalise."),
"REF-275": ("VL","Muslim 705 (Ibn Abbas): joined prayers in Madina VL.","","Number correct."),
"REF-276": ("PROSE","","HAD-BASRA-SALAT","Prose; follows REF-279 - LOCATION ERROR (see REF-279)."),
"REF-277": ("VL","Bukhari 631 (Malik b. al-Huwayrith): «صلوا كما رأيتموني أصلي» VL; also 6008.","","Resolvable."),
"REF-278": ("VL","Bukhari 530 (al-Zuhri: Anas weeping in Damascus) VL.","","Resolvable."),
"REF-279": ("MM","Bukhari 784 (Imran b. Husayn) and 786 (Mutarrif) VL - the prayer behind Ali was in BASRA («صلى مع علي بالبصرة»), not Kufa. Manuscript prose says Kufa mosque → correct to Basra, or re-source the Kufa claim. «Mishkat / Tajrid al-Bukhari» are secondary.","HAD-BASRA-SALAT","Factual correction required in prose (REF-276)."),
"REF-280": ("MM","al-Hakim's wording is «رحم الله عليا، اللهم أدر الحق معه حيث دار» (Mustadrak 3:124 h. 4629; Tirmidhi 3714 VL - very da'if). «علي مع الحق والحق مع علي» wording: al-Khatib, Tarikh Baghdad 14:321; Ibn Qutayba, al-Imama wal-Siyasa. Lock which wording the book quotes.","HAD-HAQQ-ALI","Wording ≠ source cited."),
"REF-281": ("PROSE","","HAD-KHATAM-RUKU","Prose; follows REF-282."),
"REF-282": ("CAND","Abu Dharr narration with the du'a «اللهم اشرح لي صدري...» - al-Tha'labi, al-Kashf wal-Bayan on 5:55 (4:80); Shawahid al-Tanzil 1:230; Ibn Shahrashub.","HAD-KHATAM-RUKU","Lock."),
"REF-283": ("CAND","Ibn Mardawayh; al-Khatib (Ibn Abbas); Tabarani (Ammar) on 5:55 - via al-Durr al-Manthur 2:293.","HAD-KHATAM-RUKU","Lock."),
"REF-284": ("SPC","al-Kafi 2:18-19 h. 5 (bab da'a'im al-islam) - same as REF-035.","HAD-WILAYA-KAFI","Normalise."),
"REF-285": ("VL","Bukhari 528 / Muslim 667 (Abu Hurayra, river) VL.","","Numbers correct."),
"REF-286": ("SPC","Nahj al-Balagha, hikma 237 (Subhi Salih): «إن قوما عبدوا الله رغبة فتلك عبادة التجار...».","","Resolvable."),
"REF-287": ("PROSE","","HAD-FATIMA-IBADA","Prose; follows REF-294."),
"REF-288": ("PROSE","","HAD-FATIMA-IBADA","Prose; follows REF-290."),
"REF-289": ("PROSE","","HAD-ZAHRA-NAME","Prose; follows REF-291."),
"REF-290": ("CAND","«يا ملائكتي انظروا إلى أمتي فاطمة» - Bihar al-Anwar 43:172 (from Amali al-Saduq).","HAD-FATIMA-IBADA","Lock."),
"REF-291": ("SPC","'Ilal al-Shara'i' 1:180-181 (bab 142).","HAD-ZAHRA-NAME","Normalise with REF-249."),
"REF-292": ("UNID","Najran priest «ninety years» - no source.","","Attribution-only or drop."),
"REF-293": ("VL","Bukhari 6463 VL; Muslim 2816-2818 VL: «لن ينجي أحدا منكم عمله».","","Numbers correct."),
"REF-294": ("CAND","Hasan al-Basri «ما كان في هذه الأمة أعبد من فاطمة كانت تقوم حتى تتورم قدماها» - Bihar al-Anwar 43:76 (from Manaqib Ibn Shahrashub 3:341); Imam Hasan - same bab.","HAD-FATIMA-IBADA","Replace secondary English book with primary."),
"REF-295": ("UNID","Prophet-Fatima dialogue on tawfiq - no source.","","Attribution-only."),
"REF-296": ("CAND","Salat Fatima (two rak'a) - al-Tusi, Misbah al-Mutahajjid p. 300 region; Ibn Tawus, Jamal al-Usbu'.","","Replace al-islam.org with primary."),
"REF-297": ("HIST","Mizan al-Hikma ch. 261 p. 676 - secondary; each item needs primary.","","Secondary source."),
"REF-298": ("VL","Hadith Jibril (ihsan) - Muslim 8 VL; Bukhari 50.","","Resolvable."),
"REF-299": ("CAND","«العبودية خمسة أشياء» - via Mizan al-Hikma → Misbah al-Shari'a (attributed).","","Attribution-only."),
"REF-300": ("PROSE","","HAD-MUNAJAT-ALI","Prose; follows REF-301."),
"REF-301": ("CAND","«ما عبدتك خوفا من نارك ولا طمعا في جنتك» - Bihar al-Anwar 41:14 and 70:186; Ibn Abi al-Hadid, Sharh 10:157.","HAD-MUNAJAT-ALI","Lock."),
# ---------------- Part 11 ----------------
"REF-302": ("PROSE","","HAD-SALAT-BATRA","Prose; follows REF-303."),
"REF-303": ("CAND","«لا تصلوا علي الصلاة البتراء» - Ibn Hajar al-Haytami, al-Sawa'iq al-Muhriqa (Egypt ed. p. 146); Qunduzi, Yanabi' 1:37. Not in six books (corpus: none). Shia: al-Kafi 2:495 «لا تبترها».","HAD-SALAT-BATRA","Attribution-only wording; lock pages."),
"REF-304": ("PROSE","","HAD-GHADAB-WUDU","Prose; follows REF-305."),
"REF-305": ("VL","Anger→wudu: Abu Dawud 4784 VL - graded DA'IF (Albani, Arnaut); sit/lie: Abu Dawud 4782 VL - sahih (Abu Dharr).","HAD-GHADAB-WUDU","Print grade for 4784."),
"REF-306": ("PROSE","","","Prose; follows REF-307."),
"REF-307": ("VL","Moon splitting - Bukhari 3636 VL (also 3637-3638, 4864-4868); Muslim 2800-2802.","","Resolvable; «Aqaba, 14 persons» detail → sira sources."),
"REF-308": ("PROSE","","HAD-MADINAT-ILM","Prose; follows REF-309."),
"REF-309": ("MM","Tirmidhi does NOT carry «مدينة العلم»; Tirmidhi 3723 = «أنا دار الحكمة» (VL, da'if). «مدينة العلم»: al-Hakim 3:126-127 (h. 4637-4639) etc. - see REF-164.","HAD-MADINAT-ILM","Separate the two wordings."),
"REF-310": ("PROSE","","","Prose; follows REF-312."),
"REF-311": ("PROSE","","","Prose; follows REF-313."),
"REF-312": ("VL","Muslim 2581 (Abu Hurayra): «أتدرون ما المفلس» VL.","","Number correct."),
"REF-313": ("VL","Bukhari 7083 / Muslim 2888 (Abu Bakra): «إذا التقى المسلمان بسيفيهما» VL.","","Numbers correct."),
"REF-314": ("PROSE","","","Prose; follows REF-318."),
"REF-315": ("PROSE","","","Prose; follows REF-316."),
"REF-316": ("VL","Muslim 1905 (Abu Hurayra: first three judged) VL.","","Number correct."),
"REF-317": ("VL","Bukhari 3267 (Usama) VL; Muslim 2989 - standard concordance number; wording «أقتاب» not surfaced by corpus search → PAGE-CHECK.","","Bukhari confirmed."),
"REF-318": ("CAND","Lips cut with scissors of fire - Ahmad 12856 (Anas, Mi'raj); Bayhaqi, Shu'ab 1773. Not in six books.","","Lock number."),
"REF-319": ("PROSE","","","Prose; follows REF-320."),
"REF-320": ("CAND","«أخوف ما أخاف عليكم الشرك الأصغر ... الرياء» - Ahmad 23630 (Mahmud b. Labid); Bayhaqi Shu'ab 6831. Not in six books (corpus: none).","","Lock number."),
"REF-321": ("UNID","«أنا النقطة تحت الباء» - no reliable chain (later Sufi/irfani attribution). NOT VERIFIED.","HAD-NUQTA","Keep as irfani saying, never as hadith."),
"REF-322": ("HIST","Chishti saying - diwan reference.","LIT-CHISHTI","Same as REF-015."),
"REF-323": ("HIST","Jawn (freed slave of Abu Dharr) and Wahb - Abu Mikhnaf, Maqtal; Bihar al-Anwar 45:22-23.","","Page lock."),
"REF-324": ("PROSE","","","Prose; follows REF-326."),
"REF-325": ("PROSE","","HAD-NIYYA-KAZIM","Prose; follows REF-328."),
"REF-326": ("VL","Bukhari 1 / Muslim 1907 VL.","","Numbers correct."),
"REF-327": ("CAND","Mahr/debt intention - Tabarani, al-Awsat 1851 (plausible); Ahmad.","","Lock."),
"REF-328": ("SPC","al-Kafi 2:429 h. 3 (bab man yahummu bil-hasana aw al-sayyi'a) - Imam Kazim: «إذا هم العبد بالحسنة خرج نفسه طيب الريح...».","HAD-NIYYA-KAZIM","Lock."),
}

CODES = {"VL":"VERIFIED-LIVE","MM":"MISMATCH","EDN":"EDITION-NUMBER","CAND":"CANDIDATE","SPC":"SHIA-PAGE-CHECK",
         "UNID":"UNIDENTIFIED","DUP":"DUPLICATE","PROSE":"PROSE-LINE","HIST":"NON-HADITH","S181":"RESOLVED-S181","Q":"QURAN-TEXT"}

if __name__ == "__main__":
    import sys; sys.stdout.reconfigure(encoding="utf-8")
    from collections import Counter
    assert len(T) == 328, len(T)
    assert all(f"REF-{i:03d}" in T for i in range(1,329))
    c = Counter(v[0] for v in T.values())
    for k,n in c.most_common(): print(f"{n:4d}  {k:6s} {CODES[k]}")
